# Assignment 

# Q1

Yes, there is a difference in the data type of variables list_ and array_list.

The list_ variable is a list object which can contain elements of different data types, such as integers, floats, strings, etc. In this case, the elements are strings.

The array_list variable, on the other hand, is a numpy array object which contains elements of a homogeneous data type. Since the elements in the list_ variable are strings, the array_list variable will also have elements of the string data type.

To print the data types of both variables, you can use the type() function as follows:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))


Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>


# Q2

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_ variable:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list variable:")
for element in array_list:
    print(type(element))


Data type of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list variable:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3

Yes, there will be a difference in the data type of the elements present in both list_ and array_list when array_list is created with dtype=int.

When dtype=int is specified, the elements in list_ will be converted to integers before being stored in the array_list.

Here's the code to print the data type of each element in both list_ and array_list after array_list is created with dtype=int:

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_ variable:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list variable:")
for element in array_list:
    print(type(element))


Data type of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list variable:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Data type of elements in num_list variable:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

print("\nData type of elements in num_array variable:")
for sublist in num_array:
    for element in sublist:
        print(type(element))


Data type of elements in num_list variable:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data type of elements in num_array variable:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Q4

In [7]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


print("Shape of num_array:", num_array.shape)


print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


# Q5

In [8]:
import numpy as np

zeros_array = np.zeros((3, 3))

# Print the array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6

In [9]:
import numpy as np


identity_matrix = np.eye(5)


print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
